@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber
actor Administrator
participant ":System" as System

activate Administrator
    Administrator -> System : starts to display the list sorted.
    activate System
        System --> Administrator : processes the request and retrieves the list sorted.
    deactivate System
deactivate Administrator


@enduml