@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor Receptionist
participant ":System" as System

activate Receptionist
    Receptionist -> System : starts the process of registering a employee

activate System
    System --> Receptionist : records the information and notifies the success of the operation
deactivate System
deactivate Receptionist

@enduml