@startuml
skinparam monochrome false
skinparam shadowing false

title UC020 - Register SNS User

class Receptionist {
    +Username: String [PK]
    +Password: String
}

class SNSUser {
    +Name: String
    +BirthDate: Date
    +Sex: String
    +PostalAddress: String
    +PhoneNumber: String
    +EmailAddress: String
    +CitizenCardNumber: String [PK2]
    +SNSUserNumber: String [PK]
}

' Relationships
Receptionist "1" -- "1" SNSUser : registers >

@enduml
