@startuml
skinparam monochrome false
skinparam shadowing false

title UC040 - Consult users in a waiting room

class Nurse {
    +Username: String [pk]
    +Password: String
}

class SNSUser {
    +Name: String
    +BirthDate: Date
    +Sex: String
    +SNS User number: Int [pk]
    +Vaccinations: String
    +Allergies: String
}




class WaitingRoom {
    +showInformation(): void
}

' Relationships
Nurse "1" -- WaitingRoom : provides info <
SNSUser "1" -- WaitingRoom : is on >


@enduml
