@startuml
'skinparam monochrome true
'skinparam shadowing false

title UC012 - List all vaccines

class Administrator {
    +Username: String [pk]
    +Password: String
}

class Vaccine {
    +ID: Int [pk]
    +Name: String
    +Brand: String
    +Type: VaccineType
}

class Order {
    +  grouped by type
    +  listed alphabetically by name
}

' Relationships
Administrator "1" -- "1" Vaccine : lists >
Vaccine "1" -- "1" Order : grouped by >

@enduml
