@startuml
skinparam monochrome false
skinparam shadowing false

title UC041 - Record the administration of a vaccine to a SNS user

class Nurse {
    +Username: String
    +Password: String
}

class SNSUser {
    +Name: String
    +BirthDate: Date
    +Sex: String
    +SNS User number: Int
    +Vaccinations: String
    +Allergies: String
}



' Relationships
Nurse "1" -- SNSUser : vaccination and registation >


@enduml