@startuml
'skinparam monochrome true
'skinparam shadowing false

title UC030 - As SNS user use the application to schedule a vaccination

class SNSUser {
    +Username: String
    +Password: String
    +PersonalInfo: String
}

class VaccinationCenter {
    +displayScheduleOption(): void
    +selectTimeSlot(): void
    +confirmScheduling(): void
    +provideConfirmationMessage(): void
    +informUser(): void
}

' Relationships
SNSUser "1" -- "1" VaccinationCenter : schedules >
@enduml
