@startuml
'skinparam monochrome true
'skinparam shadowing false

title UC022 - Arrival of a SNS user to take the vaccine

class Receptionist {
    +Username: String [pk]
    +Password: String
}

class SNSUser {
    +Name: String
    +BirthDate: Date
    +Sex: String
    +PostalAddress: String
    +PhoneNumber: String
    +EmailAddress: String
    +CitizenCardNumber: String [pk2]
    +VaccinationScheduled: Boolean
    +SNSNumber: Int [pk]
}

' Relationships
Receptionist "1" -- "1" SNSUser : registers the arrival of >

@enduml
