@startuml
'skinparam monochrome true
'skinparam shadowing false


title UC011 - Register vaccine

class Administrator {
    +Username: String [pk]
    +Password: String
}


class Vaccine {
    +ID: Int [pk]
    +Name: String
    +Brand: String
    +Type: VaccineType
}

class VaccineType {
    +Code: Int [pk]
    +ShortDesc: String
}

class Brand {
    +Name: String
}


' Relationships
Administrator "1" -- "1" Vaccine : register >
Vaccine "1" -- "0..1" Brand : manufactures <
Vaccine "1" -- "1" VaccineType : is of >


@enduml