@startuml
'skinparam monochrome true
'skinparam shadowing false

class Vaccine {

}

class VaccineType{
}

class lot {
}

class VaccinationAppointment {
}

class CheckIn{
}

class VaccinationCall{
}

class VaccineAdministration {
}

class VaccinationRegist {
}

class Administrator {
}

class Receptionist {
}

class Nurse {
}

class SNSUser {
}

class WaitingRoom {
}

class RecoveryRoom {
}

class AdverseReactionRecord {
}

class EUCOVIDDigitalCertificate {
}

class SNSUserRecord {
}

' Relationships
VaccinationAppointment --|> SNSUser
VaccineAdministration --|> SNSUser



@enduml