@startuml
'skinparam monochrome true
'skinparam shadowing false

title UC010 - Specify a new vaccine type


class Vaccine {
    +ID: Int [PK]
    +Nome: String
}

class VaccineType{
    +Code: Int [PK]
    +ShortDesc: String
}

class VaccineTech{
    +Name: String
    +Description: String
}

class Brand {
    +Nome: String [PK]
}

' Relationships
VaccineTech "1   "-"    *" VaccineType : is of <
VaccineType "1   "-"    *"Vaccine
Brand "1   "-"    *" Vaccine : manufactured by <

@enduml