@startuml
'skinparam monochrome true
'skinparam shadowing false

title UC015 - List employees with a role

class Administrator {
    +Username: String [PK]
    +Password: String
}

class Employee {
    +Name: String
    +Role: String
    +ID: Int [PK]
}

class Order {
    +  grouped by role
    +  listed alphabetically by name
}
' Relationships
Administrator "1" -- "  1" Employee : List >
Employee "1" -- "  1" Order : order by <



@enduml
