@startuml
'skinparam monochrome true
'skinparam shadowing false

title UC013 - Register vaccination center

class Administrator {
    +Username: String
    +Password: String
}

class VaccinationCenter {
    +ID: Int [PK]
    +Name: String
    +Location: String
    +ContactInformation: String
    +OperatingHours: String
}

class Pandemic {
    +ID: Int [PK]
    +Name: String
}

class VaccineType {
    +ID: Int [PK]
    +Name: String
    +Brand ID: String [FK]
}

' Relationships
Administrator "1" -- "1" VaccinationCenter : registers >
VaccinationCenter "1" -- "1" VaccineType : uses >
VaccineType "1" -- "0..1" Pandemic : fights >
VaccinationCenter "1" -- "1" Pandemic : cause of creation <

@enduml
