@startuml
'skinparam monochrome true
'skinparam shadowing false

title UC013 - Register vaccination center

class Administrator {
    +Username: String [pk]
    +Password: String
}

class VaccinationCenter {
    +Name: String
    +Location: String
    +ContactInformation: String
    +OperatingHours: String
    +ID: Int [pk]
}

class Pandemic {
    +Name: String [fk]
}

class VaccineType {
  +ID: Int [pk]
  +Name: String
  +Brand: String
}

' Relationships
Administrator "1" -- "1" VaccinationCenter : registers >
VaccinationCenter "1" -- "1" VaccineType : uses >
VaccineType "1" -- "0" Pandemic : fights >
VaccinationCenter "1" -- "1" Pandemic : cause of creation <

@enduml
