@startuml
'skinparam monochrome true
'skinparam shadowing false

title UC021 - Schedule a vaccination

class Receptionist {
    +Username: String
    +Password: String
}

class User {
    +Name: String
    +BirthDate: Date
    +Sex: String
    +PostalAddress: String
    +PhoneNumber: String
    +EmailAddress: String
    +CitizenCardNumber: String
    +VaccinationScheduled: Boolean
}

' Relationships
Receptionist "1" -- "1" User : schedules for >
Receptionist "1" -- "1" User : notifies >

@enduml